apiVersion: v1
kind: PersistentVolume
metadata:
  name: ubuntu-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"  # Change this to an appropriate path on your host
